main.plugins.auto_backup.enabled = false
main.plugins.auto_backup.interval = 1
main.plugins.auto_backup.max_tries = 10
main.plugins.auto_backup.files = [
 "/root/brain.nn",
 "/root/brain.json",
 "/root/.api-report.json",
 "/root/handshakes/",
 "/root/peers/",
 "/etc/pwnagotchi/",
 "/var/log/pwnagotchi.log",
]
main.plugins.auto_backup.commands = [
"tar czf /root/pwnagotchi-backup$(date +%d-%m-%Y).tar.gz {files}"
]