   main.plugins.exp.enabled = false
   main.plugins.exp.lvl_x_coord = 0
   main.plugins.exp.lvl_y_coord = 81
   main.plugins.exp.exp_x_coord = 38
   main.plugins.exp.exp_y_coord = 81
   main.plugins.exp.bar_symbols_count = 12