main.plugins.expv2.enabled = false
main.plugins.expv2.lvl_x_coord = 0
main.plugins.expv2.lvl_y_coord = 81
main.plugins.exv2p.exp_x_coord = 38
main.plugins.expv2.exp_y_coord = 81
main.plugins.expv2.bar_symbols_count = 12